In [2]:
import numpy as np
from scipy.linalg import solve_toeplitz, toeplitz, inv

c = np.array([85, 3, 6, 10])    # First column of T
b = np.array([8, 2, -56, 5])     # T*x = b
x = solve_toeplitz(c, b)
print("Con Levinson Durbin")
print(x)

Con Levinson Durbin
[ 0.13263823  0.03802353 -0.67179572  0.06424546]


In [ ]:
T = toeplitz(c)
print(T)

[[85  3  6 10]
 [ 3 85  3  6]
 [ 6  3 85  3]
 [10  6  3 85]]


In [ ]:
print("Inversión matricial tradicional")
inv(T).dot(b)

Inversión matricial tradicional


array([ 0.13263823,  0.03802353, -0.67179572,  0.06424546])

In [5]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample."]])
vectorizer = TextVectorization(output_mode="int")
vectorizer.adapt(training_data)
integer_data = vectorizer(training_data) 
print(integer_data)

tf.Tensor(
[[4 5 2 9 3]
 [7 6 2 8 3]], shape=(2, 5), dtype=int64)


In [9]:
integer_data2 = vectorizer(["This and sample HOOLA"])

In [10]:
print(integer_data2)

tf.Tensor([[4 7 3 1]], shape=(1, 4), dtype=int64)


In [25]:
from tensorflow.keras.layers.experimental.preprocessing import Normalization
a = np.array([1, 2, 54, 7, 8]).astype("float32")
normalizer = Normalization()
normalizer.adapt(a)
normalized_data = normalizer(a) 

In [28]:
np.var(normalized_data)

1.0

In [29]:
b = [5 ,8,10,25]
normalized_data_b = normalizer(b) 
print(normalized_data_b)

tf.Tensor(
[[-0.47032934]
 [-0.32022423]
 [-0.22015415]
 [ 0.5303714 ]], shape=(4, 1), dtype=float32)
